import { auth } from '@clerk/nextjs/server';
import { db } from '@/lib/db';
import { apiError } from '@/types';

export async function POST(req: Request) {
  const { userId } = auth();
  if (!userId) return Response.json(apiError('UNAUTHORIZED', 'Not authenticated'), { status: 401 });

  const user = await db.user.findUnique({ where: { clerkId: userId } });
  if (!user) return Response.json(apiError('USER_NOT_FOUND', 'User not found'), { status: 404 });

  const { queryIds, insightIds, title } = await req.json();

  const [queries, insights] = await Promise.all([
    queryIds?.length
      ? db.query.findMany({ where: { id: { in: queryIds }, userId: user.id } })
      : Promise.resolve([]),
    insightIds?.length
      ? db.insight.findMany({ where: { id: { in: insightIds } } })
      : Promise.resolve([]),
  ]);

  const html = buildReportHTML(title || 'Analysis Report', queries, insights);

  // Return HTML for client-side PDF generation (jsPDF handles conversion in browser)
  return new Response(html, {
    headers: { 'Content-Type': 'text/html' },
  });
}

function buildReportHTML(title: string, queries: any[], insights: any[]): string {
  const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #111827; margin: 0; padding: 40px; }
  .header { border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 32px; }
  .logo { font-size: 20px; font-weight: 700; color: #2563eb; }
  h1 { font-size: 28px; font-weight: 700; margin: 8px 0 4px; }
  .date { color: #6b7280; font-size: 14px; }
  .section { margin-bottom: 32px; }
  h2 { font-size: 18px; font-weight: 600; color: #1f2937; border-left: 4px solid #2563eb; padding-left: 12px; margin-bottom: 16px; }
  .query-card { background: #f9fafb; border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 16px; }
  .question { font-weight: 600; color: #1f2937; margin-bottom: 8px; }
  .answer { color: #374151; line-height: 1.6; }
  .insight-card { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 12px; }
  .insight-title { font-weight: 600; margin-bottom: 4px; }
  .insight-desc { color: #6b7280; font-size: 14px; line-height: 1.5; }
  .confidence { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 12px; font-weight: 500; margin-top: 8px; }
  .high { background: #d1fae5; color: #065f46; }
  .medium { background: #fef3c7; color: #92400e; }
  .low { background: #fee2e2; color: #991b1b; }
  .footer { margin-top: 48px; padding-top: 16px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; text-align: center; }
</style>
</head>
<body>
  <div class="header">
    <div class="logo">InsightForge</div>
    <h1>${title}</h1>
    <div class="date">Generated on ${now}</div>
  </div>

  ${queries.length > 0 ? `
  <div class="section">
    <h2>Analysis Queries (${queries.length})</h2>
    ${queries.map(q => `
      <div class="query-card">
        <div class="question">Q: ${q.questionText}</div>
        ${q.answerText ? `<div class="answer">${q.answerText}</div>` : ''}
      </div>
    `).join('')}
  </div>` : ''}

  ${insights.length > 0 ? `
  <div class="section">
    <h2>Key Insights (${insights.length})</h2>
    ${insights.map(i => `
      <div class="insight-card">
        <div class="insight-title">${i.title}</div>
        <div class="insight-desc">${i.description}</div>
        <span class="confidence ${i.confidence}">${i.confidence} confidence</span>
      </div>
    `).join('')}
  </div>` : ''}

  <div class="footer">Generated by InsightForge · AI-Powered Data Analysis</div>
</body>
</html>`;
}
