// AUTO-GENERATED by shadcn/ui CLI
// Run: npx shadcn-ui@latest add card
// Do not manually implement this file — let the CLI generate it
// Then customize the default styles to match your brand colors if needed
